services:
  server:
    image: ghcr.io/khanh29204/code-push-server:latest
    container_name: code-push-server
    volumes:
      - ./data:/data
    env_file:
      - .env
    ports:
      - '3000:3000'
    networks:
      - redis_private_net
    entrypoint:
      - /bin/sh
      - -c
      - >
        mkdir -p /data/logs &&
        exec /app/code-push-server
        1>> /data/logs/combined.log
        2>> /data/logs/combined-error.log
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  redis_private_net:
    external: true