name: Rust CI

on:
  push:
    branches:
      - master
    paths:
      - 'rust/**'
  pull_request:
    branches:
      - master
    paths:
      - 'rust/**'

jobs:
  rust-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy

      - name: Cargo Build
        working-directory: ./rust
        run: cargo build --release

      - name: Cargo Test
        working-directory: ./rust
        run: cargo test

      - name: Cargo Clippy
        working-directory: ./rust
        run: cargo clippy -- -D warnings
